---
- name: "update apt packages"
  become: true
  become_method: sudo
  apt:
    update_cache: yes

- name: "Remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: yes

# nodejs installation below is following instructions from https://kyle.pericak.com/nodejs-ansible.html
- name: "Add nodejs apt key"
  become: true
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: "Add nodejs 13.x ppa for apt repo"
  apt_repository:
    repo: deb https://deb.nodesource.com/node_13.x bionic main
    update_cache: yes

- name: "Install nodejs"
  apt:
    update_cache: yes
    name: nodejs
    state: present

- name: "Install NPM-distributed command-line tools"
  npm:
    global: yes
    name: "{{ item }}"
  with_items:
    - pm2

- name: install all modules that are listed on package.json file and their dependencies
  command: npm install

- name: stop default npm script via pm2
  command: pm2 stop default

- name:  run built-in npm script via pm2
  command: pm2 start npm -- start